/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IETHDEXV1 } from "./IETHDEXV1";
export type { ILender } from "./ILender";
export type { IPausable } from "./IPausable";
